import {
  BadRequestError,
  HashingError,
  InternalServerError,
  UnprocessableEntityError,
} from "@/exceptions";
import argon2, { argon2id } from "argon2";
import crpyto from "crypto";

export class ArgonService {
  public async hash(password: string): Promise<string> {
    if (!password || typeof password !== "string") {
      throw new BadRequestError("Password must be a non-empty string.");
    }

    if (password.length > 1024) {
      throw new UnprocessableEntityError(
        "Password exceeds maximum allowed length of 1024 characters.",
        { maxLength: 1024, receivedLength: password.length },
      );
    }

    const ARGON2_CONFIG = {
      type: argon2id,
      memoryCost: 65536,
      timeCost: 3,
      parallelism: 4,
      hashLength: 32,
    };

    try {
      const passwordHashing = await argon2.hash(password, {
        ...ARGON2_CONFIG,
        salt: crpyto.randomBytes(16),
      });

      return passwordHashing;
    } catch (error) {
      if (error instanceof Error && error.message.includes("memory")) {
        throw new HashingError("Hashing failed due to insufficient memory allocation.", {
          memoryCost: ARGON2_CONFIG.memoryCost,
          suggestion: "Reduce memoryCost or upgrade server resources.",
        });
      }

      if (error instanceof Error && error.message.includes("argon2")) {
        throw new HashingError("Argon2 internal error during hashing.", {
          originalMessage: error.message,
        });
      }

      throw new InternalServerError("Unexpected error during password hashing.", {
        originalMessage: error instanceof Error ? error.message : String(error),
      });
    }
  }

  public async verify(password: string, hash: string): Promise<boolean> {
    if (!password || !hash) {
      throw new BadRequestError("Both password and hash are required.", {
        password: !password ? "missing" : "ok",
        hash: !hash ? "missing" : "ok",
      });
    }

    try {
      return await argon2.verify(hash, password);
    } catch (error) {
      if (error instanceof Error && error.message.includes("invalid hash")) {
        throw new UnprocessableEntityError("Provided hash is malformed or corrupted.", {
          hint: "Ensure the hash was generated by argon2 and has not been tampered with.",
        });
      }

      throw new InternalServerError("Unexpected error during password verification.", {
        originalMessage: error instanceof Error ? error.message : String(error),
      });
    }
  }
}
